---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: ledger-api-secrets
  namespace: payments
spec:
  encryptedData:
    DB_PASSWORD: AgAxoqYQdjXmUqbPe6c2czUCHobi6Lrv7BGLd5JRdbEffvPjSG+QZJ6VDZwMjijAISmZaPprbbhz+ORTx603JhKo9zc/xuZH4LYEYNI0JQrnHypmzw6AwCdCvrknPgwAHwutN6cgcfZEXk6wlIR/UId2WiNP+WFKGndo6B2tXuu3rOWlgh2GgFHu7h/sjAVNLLqlW+/JV5DKuGG1jWm7qvMNGaGYDzjwThNAS+14NZbZ8R0c+UAUikjW/pFwEcF2BUHW0Zcq5J+WtqKu0WO3jkWamDUmtpOsOxWMMD0L3dFuBh8u7zVWccxZTqkOdo/LgmAZ429hmy7/Bq3EbN5+wys/UDAPCDlNtIL8l6L4z47DS6dES7mkE6t6NdlWFx+J8RWicmv+V/khq+J8F9vfvIvSzR423POfXfoKGMhmwS+HKqv8Sx3Ulvg5GiJMF9eW6JRssx/wYA8T+n/LP6Mc9yi8WrRPEExjH+1Dnmy0HTusJafg9G0M3FNjzfwx0zWsbUTWNyhWN4avsSzALvQWxVzYfsgej+mOsHbPzxD2ch2+keSPwfAQui06Kt/3Y2op6qTfgZ+b3RuL4nuRbCpPZts/S5vWGUWVpwTRKgXe5mfU5Ra6CE2gQ4AJHcAe9EkgP59IfZ0//9lwxbKxzg8ghoL5EyBUMHYy3jHYnCNdf0od4QW9y0+8oJBf9Uwcjp7I/FfiRc3wv45r0JTf0w==
    STRIPE_API_KEY: AgBjdsMpv/i2ySaycWXHXsYVVubN5I8f4DF8nnh1VSOzBfcSZ43hYGqUEVdL3CiIYMQewxOuhsY+HRUu/bVtALksuJ52NZPYo/jBeS0hiIFJ0XsRmu2aEQV2pgu2Bo1XkJ+KVcv3/gAOyNXCpXXuT+CioTBbsYG6ynU5c0d2SJ7y3vsEGnNDQdf6GLXIxja6HHtXbSJBv/4YZHNHuNqz7vUGk3625DGN39W2xbQO3w6vvZeZx654mmpZluGExswM+v9rfcGPl90J72z/KJ2v//OpLfGXhSHhVDHdhLgul/EziZjfkr5YlXcYilGvCEQ+++YOd8qDsFM9vjyyEn8d44KSqjGpkQ9NMg0G/+iS2/eCj7ZOxuvymVepqNZop7jA/VOoiC7nnYXHa2yypHAL74e9Uft9o4pNdtp3U4AyFQ2LH5Pwvjn6nci//w86w2Aww/jXCqchQoOI+mSWQXGL55xKoVwqgCeh6I5W8bI5O/qkq2UaYPAzHDk8khDd/OWDH/Pr5y1ZvoMUyvqKNDWErGxcEGiB6yuFbeRpyaR55NHeMlX+g41ZN2J9THX9+/7OVgdUtYThUbVi7nH/VywT1iYBkVG4aGozZRc1Oif3lzArUvhAKgzr2NEF1S/coHfjc/aYILTxVDjWe4aQE/H1sNMFPc7uSrk8zpPN3es9Uqcsnawspi4tzo/F6hi6GldpmoRJu+ezDAvfUnEON38Yng+VL+rAnIoWEOe6RKLOpA==
  template:
    metadata:
      creationTimestamp: null
      name: ledger-api-secrets
      namespace: payments
